# Generated by Django 3.2.5 on 2022-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howsyourday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colordecision',
            name='userText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
